Insert absolute current directory into sys.path
Using sys.path.insert(0, ".") started giving an error on
macOS Catalina (10.15.3) on "from pegen import parse":

    ImportError: dlopen(./pegen/parse.cpython-38-darwin.so, 2): no suitable image found.  Did find:
            file system relative paths not allowed in hardened programs

I'm not sure since when -- I think maybe since I installed Python
3.8.2 downloaded from python.org.